import { User } from '../models/User';
import { Department } from '../models/Department';
import { Location } from '../models/Location';
import { Asset } from '../models/Asset';
import { Maintenance } from '../models/Maintenance';
import { UsageRecord } from '../models/UsageRecord';
import { Notification } from '../models/Notification';
import { AuditLog } from '../models/AuditLog';
import { generateQRCode, generateBarcodeString } from '../utils/codeGenerators';

export async function seedDatabase() {
  console.log('--- Starting Database Seeding ---');

  // Check if already seeded with assets
  const assetCount = await Asset.countDocuments();
  if (assetCount > 0) {
    console.log(`Database already contains ${assetCount} assets. Skipping initial seed.`);
    return;
  }

  // Clear existing collections
  await Promise.all([
    User.deleteMany({}),
    Department.deleteMany({}),
    Location.deleteMany({}),
    Asset.deleteMany({}),
    Maintenance.deleteMany({}),
    UsageRecord.deleteMany({}),
    Notification.deleteMany({}),
    AuditLog.deleteMany({}),
  ]);

  // 1. Create Departments
  const departmentsData = [
    {
      name: 'Computer Science and Engineering',
      code: 'CSE',
      block: 'Block A - Turing Wing',
      headOfDepartment: 'Dr. K. S. Ramanathan',
      contactEmail: 'hod.cse@college.edu',
      contactPhone: '+91 94441 23401',
      description: 'Undergraduate and postgraduate computing laboratories, project development labs, and cloud infrastructure.',
    },
    {
      name: 'Information Technology',
      code: 'IT',
      block: 'Block B - Lovelace Wing',
      headOfDepartment: 'Dr. Meena Sundaram',
      contactEmail: 'hod.it@college.edu',
      contactPhone: '+91 94441 23402',
      description: 'Software engineering, cybersecurity, and data analytics laboratories.',
    },
    {
      name: 'Electronics and Communication',
      code: 'ECE',
      block: 'Block C - Faraday Block',
      headOfDepartment: 'Prof. R. Venkataraman',
      contactEmail: 'hod.ece@college.edu',
      contactPhone: '+91 94441 23403',
      description: 'Embedded systems, signal processing, VLSI design, and telecommunication laboratories.',
    },
    {
      name: 'Mechanical Engineering',
      code: 'MECH',
      block: 'Mechanical Workshop Complex',
      headOfDepartment: 'Dr. S. Balasubramanian',
      contactEmail: 'hod.mech@college.edu',
      contactPhone: '+91 94441 23404',
      description: 'Heavy machinery, thermal engineering, robotics, CAD/CAM, and material testing labs.',
    },
    {
      name: 'Electrical Engineering',
      code: 'EEE',
      block: 'Block D - Tesla Block',
      headOfDepartment: 'Dr. Anita Roy',
      contactEmail: 'hod.eee@college.edu',
      contactPhone: '+91 94441 23405',
      description: 'Power systems, electrical drives, high voltage, and renewable energy laboratories.',
    },
    {
      name: 'Administration',
      code: 'ADMIN',
      block: 'Administrative Heritage Block',
      headOfDepartment: 'Prof. V. Narayanan (Registrar)',
      contactEmail: 'registrar@college.edu',
      contactPhone: '+91 94441 23400',
      description: 'Campus-wide asset provisioning, executive boardrooms, stores, and central procurement.',
    },
  ];

  const createdDepts = await Department.insertMany(departmentsData);
  const deptMap: Record<string, any> = {};
  createdDepts.forEach((d) => {
    deptMap[d.code] = d;
  });

  // 2. Create Locations
  const locationsData = [
    {
      name: 'CSE Lab 1 (Programming & OS)',
      code: 'LOC-CSE-01',
      department: deptMap['CSE']._id,
      floor: '1st Floor',
      roomNumber: 'A-101',
      capacity: 65,
      inCharge: 'Er. Rajesh Kumar',
      description: 'Equipped with 60 high-performance workstations for student programming labs.',
    },
    {
      name: 'CSE Lab 2 (AI & Cloud Systems)',
      code: 'LOC-CSE-02',
      department: deptMap['CSE']._id,
      floor: '1st Floor',
      roomNumber: 'A-102',
      capacity: 45,
      inCharge: 'Mrs. Priya Selvam',
      description: 'Advanced machine learning laboratory with GPU workstations and servers.',
    },
    {
      name: 'IT Systems Lab',
      code: 'LOC-IT-01',
      department: deptMap['IT']._id,
      floor: '2nd Floor',
      roomNumber: 'B-204',
      capacity: 50,
      inCharge: 'Mr. Arvind Nathan',
      description: 'Networking, database architecture, and web systems practicals.',
    },
    {
      name: 'Electronics & Microprocessor Lab',
      code: 'LOC-ECE-01',
      department: deptMap['ECE']._id,
      floor: '3rd Floor',
      roomNumber: 'C-301',
      capacity: 40,
      inCharge: 'Er. Deepa Natarajan',
      description: 'Oscilloscopes, function generators, microcontrollers, and soldering stations.',
    },
    {
      name: 'Mechanical Workshop & Machining',
      code: 'LOC-MECH-WS',
      department: deptMap['MECH']._id,
      floor: 'Ground Floor',
      roomNumber: 'WS-01',
      capacity: 70,
      inCharge: 'Mr. Muthuvel P.',
      description: 'Lathe machines, CNC routers, drill presses, and fabrication workbenches.',
    },
    {
      name: 'Central Seminar Hall',
      code: 'LOC-SEM-01',
      department: deptMap['ADMIN']._id,
      floor: 'Ground Floor',
      roomNumber: 'SH-01',
      capacity: 250,
      inCharge: 'Campus Event Coordinator',
      description: 'Main auditorium with dual laser projection and professional PA sound system.',
    },
    {
      name: 'Central Department Store',
      code: 'LOC-STORE',
      department: deptMap['ADMIN']._id,
      floor: 'Basement / Ground Floor',
      roomNumber: 'DS-01',
      capacity: 20,
      inCharge: 'Store Officer Shanmugam',
      description: 'Central buffer stock of spare parts, cables, consumables, and standby equipment.',
    },
    {
      name: 'CSE Faculty Room',
      code: 'LOC-FAC-01',
      department: deptMap['CSE']._id,
      floor: '2nd Floor',
      roomNumber: 'A-201',
      capacity: 25,
      inCharge: 'Dr. K. S. Ramanathan',
      description: 'Faculty workstations, departmental conference table, and document printers.',
    },
  ];

  const createdLocations = await Location.insertMany(locationsData);
  const locMap: Record<string, any> = {};
  createdLocations.forEach((l) => {
    locMap[l.code] = l;
  });

  // 3. Create Seed Users
  // Note: user.save() runs bcrypt hook
  const adminUser = new User({
    name: 'Prof. Suresh Kumar (Admin)',
    email: 'admin@inventory.com',
    password: 'password123',
    role: 'ADMIN',
    department: deptMap['ADMIN']._id,
    departmentName: 'Administration',
    designation: 'Chief Systems Administrator',
    phone: '+91 98400 11221',
  });
  await adminUser.save();

  const personalAdminUser = new User({
    name: 'Eniya Siva (Admin)',
    email: 'eniyasiva2004@gmail.com',
    password: 'password123',
    role: 'ADMIN',
    department: deptMap['ADMIN']._id,
    departmentName: 'Administration',
    designation: 'Lead Systems Architect & Administrator',
    phone: '+91 98400 99887',
  });
  await personalAdminUser.save();

  // Support additional custom admin email from environment if defined
  if (process.env.ADMIN_EMAIL && process.env.ADMIN_EMAIL !== 'admin@inventory.com' && process.env.ADMIN_EMAIL !== 'eniyasiva2004@gmail.com') {
    const customAdmin = new User({
      name: 'Custom Administrator',
      email: process.env.ADMIN_EMAIL.toLowerCase().trim(),
      password: process.env.ADMIN_PASSWORD || 'password123',
      role: 'ADMIN',
      department: deptMap['ADMIN']._id,
      departmentName: 'Administration',
      designation: 'Custom Administrator',
      phone: '+91 98400 00000',
    });
    await customAdmin.save();
  }

  const staffUser = new User({
    name: 'Er. Eniya Siva (Staff)',
    email: 'staff@inventory.com',
    password: 'password123',
    role: 'STAFF',
    department: deptMap['CSE']._id,
    departmentName: 'Computer Science and Engineering',
    designation: 'Senior Laboratory Technician',
    phone: '+91 98400 33442',
  });
  await staffUser.save();

  const headUser = new User({
    name: 'Dr. K. S. Ramanathan (HOD)',
    email: 'head@inventory.com',
    password: 'password123',
    role: 'DEPARTMENT_HEAD',
    department: deptMap['CSE']._id,
    departmentName: 'Computer Science and Engineering',
    designation: 'Professor & Head of Department',
    phone: '+91 98400 55663',
  });
  await headUser.save();

  console.log('Seeded Users: Institutional Admins (admin@inventory.com, eniyasiva2004@gmail.com), Staff, Department Head');

  // 4. Create 22+ Realistic Assets
  const assetsSeedConfig = [
    {
      assetId: 'AST-2026-0001',
      name: 'Dell OptiPlex 7090 Desktop Workstation',
      category: 'Computing Equipment',
      description: 'Intel Core i7-11700, 16GB DDR4 RAM, 512GB NVMe SSD, 24" Dell Full HD Monitor. Primary student lab system.',
      deptCode: 'CSE',
      locCode: 'LOC-CSE-01',
      manufacturer: 'Dell Technologies',
      model: 'OptiPlex 7090 MT',
      serialNumber: 'DL-OPT-7090-9941A',
      purchaseDate: new Date('2023-08-15'),
      purchaseCost: 68500,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2026-08-15'),
      lastMaintenanceDate: new Date('2026-01-10'),
      nextMaintenanceDate: new Date('2026-07-10'),
    },
    {
      assetId: 'AST-2026-0002',
      name: 'HP LaserJet Pro M404dn Network Printer',
      category: 'Computing Equipment',
      description: 'Heavy-duty duplex monochrome laser printer connected to college network for assignment and paper submissions.',
      deptCode: 'CSE',
      locCode: 'LOC-CSE-01',
      manufacturer: 'HP Inc.',
      model: 'LaserJet Pro M404dn',
      serialNumber: 'HP-LJP-404-33291',
      purchaseDate: new Date('2023-01-20'),
      purchaseCost: 29500,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Good',
      status: 'Available',
      warrantyExpiry: new Date('2026-01-20'),
      lastMaintenanceDate: new Date('2026-02-15'),
      nextMaintenanceDate: new Date('2026-05-15'),
    },
    {
      assetId: 'AST-2026-0003',
      name: 'Rigol DS1054Z 50MHz 4-Channel Digital Oscilloscope',
      category: 'Laboratory Instruments',
      description: '4-channel digital storage oscilloscope with 1GSa/s real-time sample rate for signal measurements in electronics labs.',
      deptCode: 'ECE',
      locCode: 'LOC-ECE-01',
      manufacturer: 'Rigol Technologies',
      model: 'DS1054Z',
      serialNumber: 'RG-DS-1054-7721B',
      purchaseDate: new Date('2023-03-10'),
      purchaseCost: 38000,
      quantity: 1,
      availableQuantity: 0,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Good',
      status: 'In Use',
      assignedTo: staffUser._id,
      assignedDate: new Date('2026-09-28'),
      warrantyExpiry: new Date('2026-03-10'),
      lastMaintenanceDate: new Date('2026-01-05'),
      nextMaintenanceDate: new Date('2026-06-05'),
    },
    {
      assetId: 'AST-2026-0004',
      name: 'Fluke 115 True-RMS Digital Multimeter',
      category: 'Laboratory Instruments',
      description: 'Compact True-RMS multimeter for technicians, calibrated for voltage, resistance, continuity, and capacitance testing.',
      deptCode: 'ECE',
      locCode: 'LOC-ECE-01',
      manufacturer: 'Fluke Corporation',
      model: 'Fluke 115',
      serialNumber: 'FLK-115-48201',
      purchaseDate: new Date('2024-02-14'),
      purchaseCost: 18500,
      quantity: 5,
      availableQuantity: 4,
      minimumStockLevel: 2,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2027-02-14'),
      lastMaintenanceDate: new Date('2026-02-01'),
      nextMaintenanceDate: new Date('2026-08-01'),
    },
    {
      assetId: 'AST-2026-0005',
      name: 'Epson EB-X06 3600-Lumens 3LCD Projector',
      category: 'Audio-Visual & Presentation',
      description: 'High-brightness overhead projector with HDMI & VGA connectivity for lectures and seminar presentations.',
      deptCode: 'ADMIN',
      locCode: 'LOC-SEM-01',
      manufacturer: 'Epson Corporation',
      model: 'EB-X06',
      serialNumber: 'EP-EBX-06-8910',
      purchaseDate: new Date('2023-09-05'),
      purchaseCost: 42000,
      quantity: 1,
      availableQuantity: 0,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Fair',
      status: 'Under Maintenance',
      warrantyExpiry: new Date('2025-09-05'),
      lastMaintenanceDate: new Date('2026-02-10'),
      nextMaintenanceDate: new Date('2026-10-02'),
    },
    {
      assetId: 'AST-2026-0006',
      name: 'APC Smart-UPS 2200VA LCD 230V SmartConnect',
      category: 'Power & Backup',
      description: 'Sine-wave battery backup for central server rack and networking equipment with remote monitoring card.',
      deptCode: 'CSE',
      locCode: 'LOC-CSE-02',
      manufacturer: 'Schneider Electric / APC',
      model: 'SMT2200IC',
      serialNumber: 'APC-SMT-2200-5541',
      purchaseDate: new Date('2022-11-12'),
      purchaseCost: 74000,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Good',
      status: 'Available',
      warrantyExpiry: new Date('2025-11-12'),
      lastMaintenanceDate: new Date('2026-01-20'),
      nextMaintenanceDate: new Date('2026-04-20'),
    },
    {
      assetId: 'AST-2026-0007',
      name: 'Cisco Catalyst 2960-X 48-Port Gigabit Switch',
      category: 'Networking & Servers',
      description: 'Enterprise managed stackable Ethernet switch connecting all client machines in CSE Lab 1 to the core campus fiber backbone.',
      deptCode: 'CSE',
      locCode: 'LOC-CSE-01',
      manufacturer: 'Cisco Systems',
      model: 'WS-C2960X-48TS-L',
      serialNumber: 'CSCO-2960X-48892',
      purchaseDate: new Date('2022-06-25'),
      purchaseCost: 98000,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2027-06-25'),
      lastMaintenanceDate: new Date('2026-03-01'),
      nextMaintenanceDate: new Date('2026-09-01'),
    },
    {
      assetId: 'AST-2026-0008',
      name: 'Hakko FX-888D Digital Soldering Station',
      category: 'Tools & Machinery',
      description: 'Microprocessor-controlled temperature adjustable soldering station with digital display for electronic fabrication.',
      deptCode: 'ECE',
      locCode: 'LOC-ECE-01',
      manufacturer: 'Hakko Corporation',
      model: 'FX-888D',
      serialNumber: 'HK-FX-888-2911A',
      purchaseDate: new Date('2024-01-18'),
      purchaseCost: 14500,
      quantity: 8,
      availableQuantity: 7,
      minimumStockLevel: 2,
      unit: 'Sets',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2026-01-18'),
      lastMaintenanceDate: new Date('2026-02-12'),
      nextMaintenanceDate: new Date('2026-08-12'),
    },
    {
      assetId: 'AST-2026-0009',
      name: 'MakerBot Replicator+ Desktop 3D Printer',
      category: 'Tools & Machinery',
      description: 'Rapid prototyping additive manufacturing 3D printer for student engineering projects and prototype fabrication.',
      deptCode: 'MECH',
      locCode: 'LOC-MECH-WS',
      manufacturer: 'MakerBot Industries',
      model: 'Replicator Plus',
      serialNumber: 'MB-REP-PLUS-1049',
      purchaseDate: new Date('2023-07-22'),
      purchaseCost: 185000,
      quantity: 1,
      availableQuantity: 0,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Good',
      status: 'In Use',
      assignedTo: staffUser._id,
      assignedDate: new Date('2026-09-29'),
      warrantyExpiry: new Date('2026-07-22'),
      lastMaintenanceDate: new Date('2026-01-15'),
      nextMaintenanceDate: new Date('2026-07-15'),
    },
    {
      assetId: 'AST-2026-0010',
      name: 'Arduino Uno Rev3 Microcontroller Starter Kit',
      category: 'Laboratory Instruments',
      description: 'Comprehensive kit including ATmega328P microcontroller board, jumper wires, sensors, LCD displays, and breadboards.',
      deptCode: 'CSE',
      locCode: 'LOC-STORE',
      manufacturer: 'Arduino Official',
      model: 'A000066-KIT',
      serialNumber: 'ARD-UNO-R3-K081',
      purchaseDate: new Date('2024-06-10'),
      purchaseCost: 3200,
      quantity: 25,
      availableQuantity: 4, // LOW STOCK TRIGGER (threshold is 6)
      minimumStockLevel: 6,
      unit: 'Kits',
      condition: 'Good',
      status: 'Available',
      warrantyExpiry: new Date('2026-06-10'),
      lastMaintenanceDate: null,
      nextMaintenanceDate: null,
    },
    {
      assetId: 'AST-2026-0011',
      name: 'Raspberry Pi 4 Model B (8GB RAM)',
      category: 'Computing Equipment',
      description: 'Broadcom BCM2711 quad-core Cortex-A72 board with dual 4K micro-HDMI, gigabit ethernet, for IoT development experiments.',
      deptCode: 'IT',
      locCode: 'LOC-IT-01',
      manufacturer: 'Raspberry Pi Foundation',
      model: 'Pi 4B 8GB',
      serialNumber: 'RPI-4B8-60193',
      purchaseDate: new Date('2024-04-12'),
      purchaseCost: 7800,
      quantity: 15,
      availableQuantity: 3, // LOW STOCK TRIGGER (threshold is 5)
      minimumStockLevel: 5,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2026-04-12'),
      lastMaintenanceDate: null,
      nextMaintenanceDate: null,
    },
    {
      assetId: 'AST-2026-0012',
      name: 'Bosch Professional Rotary Hammer Drill GBH 2-26',
      category: 'Tools & Machinery',
      description: 'Heavy duty electro-pneumatic hammer drill for workshop fabrication, mounting fixtures, and structural test rigs.',
      deptCode: 'MECH',
      locCode: 'LOC-MECH-WS',
      manufacturer: 'Robert Bosch GmbH',
      model: 'GBH 2-26 DRE',
      serialNumber: 'BSH-GBH-226-901',
      purchaseDate: new Date('2022-04-10'),
      purchaseCost: 12500,
      quantity: 2,
      availableQuantity: 2,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Good',
      status: 'Available',
      warrantyExpiry: new Date('2025-04-10'),
      lastMaintenanceDate: new Date('2026-02-18'),
      nextMaintenanceDate: new Date('2026-08-18'),
    },
    {
      assetId: 'AST-2026-0013',
      name: 'Ergonomic Mesh High-Back Faculty Chair',
      category: 'Furniture & Fixtures',
      description: 'Synchro-tilt mechanism with pneumatic height adjustment and adjustable lumbar support for department faculty.',
      deptCode: 'CSE',
      locCode: 'LOC-FAC-01',
      manufacturer: 'Featherlite Furniture',
      model: 'Optima High Back',
      serialNumber: 'FTH-OPT-77401',
      purchaseDate: new Date('2023-11-20'),
      purchaseCost: 11200,
      quantity: 12,
      availableQuantity: 12,
      minimumStockLevel: 2,
      unit: 'Chairs',
      condition: 'Good',
      status: 'Available',
      warrantyExpiry: new Date('2026-11-20'),
      lastMaintenanceDate: null,
      nextMaintenanceDate: null,
    },
    {
      assetId: 'AST-2026-0014',
      name: 'Keyence Binocular Optical Inspection Microscope',
      category: 'Laboratory Instruments',
      description: 'Stereoscopic microscope with continuous zoom 10x-50x with ring LED illuminator for PCB defect inspection.',
      deptCode: 'ECE',
      locCode: 'LOC-ECE-01',
      manufacturer: 'Keyence Corp',
      model: 'SZ-61 Stereo',
      serialNumber: 'KYN-SZ-610-822',
      purchaseDate: new Date('2023-05-18'),
      purchaseCost: 92000,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2026-05-18'),
      lastMaintenanceDate: new Date('2026-01-12'),
      nextMaintenanceDate: new Date('2026-07-12'),
    },
    {
      assetId: 'AST-2026-0015',
      name: 'Interactive Smart Touch Whiteboard 75-inch',
      category: 'Audio-Visual & Presentation',
      description: '4K UHD 20-point touch interactive display with wireless screen casting for Seminar Hall presentations and defense meetings.',
      deptCode: 'ADMIN',
      locCode: 'LOC-SEM-01',
      manufacturer: 'ViewSonic Corporation',
      model: 'ViewBoard IFP7550',
      serialNumber: 'VS-IFP-7550-993',
      purchaseDate: new Date('2024-03-01'),
      purchaseCost: 165000,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2027-03-01'),
      lastMaintenanceDate: new Date('2026-02-28'),
      nextMaintenanceDate: new Date('2026-08-28'),
    },
    {
      assetId: 'AST-2026-0016',
      name: 'Lenovo ThinkCentre M70q Tiny Desktop',
      category: 'Computing Equipment',
      description: 'Compact ultra-small-form-factor desktop running specialized lab monitoring and attendance biometric software.',
      deptCode: 'CSE',
      locCode: 'LOC-CSE-02',
      manufacturer: 'Lenovo Group',
      model: 'ThinkCentre M70q Gen 3',
      serialNumber: 'LNV-TC-M70-1102A',
      purchaseDate: new Date('2024-02-10'),
      purchaseCost: 54000,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2027-02-10'),
      lastMaintenanceDate: null,
      nextMaintenanceDate: new Date('2026-11-10'),
    },
    {
      assetId: 'AST-2026-0017',
      name: 'Canon imageRUNNER 2625i Multi-Function Copier',
      category: 'Computing Equipment',
      description: 'A3 monochrome multifunction network copier, scanner, and printer for semester examination paper preparation.',
      deptCode: 'ADMIN',
      locCode: 'LOC-STORE',
      manufacturer: 'Canon Inc.',
      model: 'iR 2625i',
      serialNumber: 'CN-IR-2625-7833',
      purchaseDate: new Date('2022-10-15'),
      purchaseCost: 135000,
      quantity: 1,
      availableQuantity: 0,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Fair',
      status: 'Under Maintenance',
      warrantyExpiry: new Date('2025-10-15'),
      lastMaintenanceDate: new Date('2026-02-05'),
      nextMaintenanceDate: new Date('2026-10-05'),
    },
    {
      assetId: 'AST-2026-0018',
      name: 'Cat6 UTP Ethernet Patch Cable Reel (305m)',
      category: 'Consumables & Supplies',
      description: 'Pure copper 4-pair 23AWG unshielded twisted pair network cable drum for laboratory patch leads and network drops.',
      deptCode: 'CSE',
      locCode: 'LOC-STORE',
      manufacturer: 'D-Link Corporation',
      model: 'NCB-C6UGRYR-305',
      serialNumber: 'DLK-CAT6-DRUM-09',
      purchaseDate: new Date('2024-05-15'),
      purchaseCost: 9800,
      quantity: 6,
      availableQuantity: 1, // LOW STOCK TRIGGER (threshold 2)
      minimumStockLevel: 2,
      unit: 'Reels',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: null,
      lastMaintenanceDate: null,
      nextMaintenanceDate: null,
    },
    {
      assetId: 'AST-2026-0019',
      name: 'Precision Lead-Free Solder Wire Reel (500g)',
      category: 'Consumables & Supplies',
      description: 'SAC305 rosin-core solder wire for electronics assembly, prototyping, and component rework.',
      deptCode: 'ECE',
      locCode: 'LOC-STORE',
      manufacturer: 'Kester Solder',
      model: 'Kester 24-7068-7600',
      serialNumber: 'KST-SLD-500G-44',
      purchaseDate: new Date('2024-07-01'),
      purchaseCost: 3400,
      quantity: 10,
      availableQuantity: 2, // LOW STOCK TRIGGER (threshold 3)
      minimumStockLevel: 3,
      unit: 'Reels',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: null,
      lastMaintenanceDate: null,
      nextMaintenanceDate: null,
    },
    {
      assetId: 'AST-2026-0020',
      name: 'Workshop Precision Bench Lathe Machine 1.5 HP',
      category: 'Tools & Machinery',
      description: 'Heavy duty metal turning center with 3-jaw chuck, metric lead screw, and digital readout for mechanical engineering workshop.',
      deptCode: 'MECH',
      locCode: 'LOC-MECH-WS',
      manufacturer: 'Kirloskar Machine Tools',
      model: 'TurnMaster 35',
      serialNumber: 'KRL-TM35-20198',
      purchaseDate: new Date('2021-08-30'),
      purchaseCost: 245000,
      quantity: 1,
      availableQuantity: 1,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Good',
      status: 'Available',
      warrantyExpiry: new Date('2024-08-30'),
      lastMaintenanceDate: new Date('2026-01-25'),
      nextMaintenanceDate: new Date('2026-07-25'),
    },
    {
      assetId: 'AST-2026-0021',
      name: 'Digital Arbitrary Waveform Generator 25MHz',
      category: 'Laboratory Instruments',
      description: 'Dual channel DDS arbitrary waveform function generator with 200MSa/s sampling rate for electronics communication labs.',
      deptCode: 'ECE',
      locCode: 'LOC-ECE-01',
      manufacturer: 'Siglent Technologies',
      model: 'SDG1025',
      serialNumber: 'SGL-SDG-1025-502',
      purchaseDate: new Date('2023-11-05'),
      purchaseCost: 26000,
      quantity: 1,
      availableQuantity: 0,
      minimumStockLevel: 1,
      unit: 'Units',
      condition: 'Poor',
      status: 'Damaged',
      warrantyExpiry: new Date('2026-11-05'),
      lastMaintenanceDate: new Date('2026-02-01'),
      nextMaintenanceDate: new Date('2026-10-01'),
    },
    {
      assetId: 'AST-2026-0022',
      name: 'Sony Professional Wireless Collar Microphone Set',
      category: 'Audio-Visual & Presentation',
      description: 'UWP-D21 wireless lavalier microphone bodypack and diversity tuner receiver for auditorium lectures.',
      deptCode: 'ADMIN',
      locCode: 'LOC-SEM-01',
      manufacturer: 'Sony Corporation',
      model: 'UWP-D21',
      serialNumber: 'SNY-UWP-D21-889',
      purchaseDate: new Date('2023-04-14'),
      purchaseCost: 46000,
      quantity: 2,
      availableQuantity: 2,
      minimumStockLevel: 1,
      unit: 'Sets',
      condition: 'Excellent',
      status: 'Available',
      warrantyExpiry: new Date('2026-04-14'),
      lastMaintenanceDate: new Date('2026-01-15'),
      nextMaintenanceDate: new Date('2026-07-15'),
    },
  ];

  const createdAssets: any[] = [];
  for (const cfg of assetsSeedConfig) {
    const qrDataUrl = await generateQRCode(cfg.assetId, cfg.name);
    const barcodeStr = generateBarcodeString(cfg.assetId);

    const assetDoc = new Asset({
      assetId: cfg.assetId,
      name: cfg.name,
      category: cfg.category,
      description: cfg.description,
      department: deptMap[cfg.deptCode]._id,
      location: locMap[cfg.locCode]._id,
      manufacturer: cfg.manufacturer,
      model: cfg.model,
      serialNumber: cfg.serialNumber,
      purchaseDate: cfg.purchaseDate,
      purchaseCost: cfg.purchaseCost,
      quantity: cfg.quantity,
      availableQuantity: cfg.availableQuantity,
      minimumStockLevel: cfg.minimumStockLevel,
      unit: cfg.unit,
      condition: cfg.condition,
      status: cfg.status,
      assignedTo: cfg.assignedTo || null,
      assignedDate: cfg.assignedDate || null,
      warrantyExpiry: cfg.warrantyExpiry,
      lastMaintenanceDate: cfg.lastMaintenanceDate,
      nextMaintenanceDate: cfg.nextMaintenanceDate,
      qrCode: qrDataUrl,
      barcode: barcodeStr,
    });
    const saved = await assetDoc.save();
    createdAssets.push(saved);
  }

  console.log(`Seeded ${createdAssets.length} Assets with dynamic QR codes & Barcodes.`);

  // 5. Create Maintenance Records
  const maintenanceRecords = [
    {
      asset: createdAssets[4]._id, // Epson Projector
      maintenanceType: 'Corrective',
      scheduledDate: new Date('2026-09-25'),
      dueDate: new Date('2026-10-02'),
      technician: 'Vignesh AV Support Solutions',
      cost: 4500,
      description: 'Optical filter cleaning and projector cooling fan replacement due to intermittent overheating during seminar lectures.',
      status: 'In Progress',
      priority: 'High',
      notes: 'Replacement fan part ordered from authorized vendor; delivery expected tomorrow.',
      scheduledBy: adminUser._id,
    },
    {
      asset: createdAssets[16]._id, // Canon Copier
      maintenanceType: 'Emergency',
      scheduledDate: new Date('2026-09-28'),
      dueDate: new Date('2026-10-01'),
      technician: 'Canon Authorized Regional Engineer (Mr. Murali)',
      cost: 8200,
      description: 'Paper pickup roller jam assembly error code E000-0010. Exam cell copier halted.',
      status: 'Scheduled',
      priority: 'Critical',
      notes: 'Priority service requested due to upcoming mid-semester examinations.',
      scheduledBy: staffUser._id,
    },
    {
      asset: createdAssets[20]._id, // Waveform Generator (Damaged)
      maintenanceType: 'Corrective',
      scheduledDate: new Date('2026-09-20'),
      dueDate: new Date('2026-09-27'), // Overdue!
      technician: 'Suresh Instrumentation Calibration Works',
      cost: 6500,
      description: 'Output port channel 1 BNC connector loose and voltage offset drifting by +1.4V.',
      status: 'Overdue',
      priority: 'High',
      notes: 'Calibration lab requested RMA return dispatch. Awaiting department head authorization.',
      scheduledBy: headUser._id,
    },
    {
      asset: createdAssets[0]._id, // Dell Desktop
      maintenanceType: 'Preventive',
      scheduledDate: new Date('2026-01-05'),
      dueDate: new Date('2026-01-10'),
      completedDate: new Date('2026-01-10'),
      technician: 'Er. Rajesh Kumar (Senior Lab Tech)',
      cost: 0,
      description: 'Semi-annual internal dust de-clogging, thermal paste replacement, BIOS firmware flash, and OS patch updates.',
      status: 'Completed',
      priority: 'Medium',
      notes: 'Passed hardware self-test diagnostic with zero errors.',
      scheduledBy: adminUser._id,
    },
    {
      asset: createdAssets[2]._id, // Rigol Oscilloscope
      maintenanceType: 'Preventive',
      scheduledDate: new Date('2025-12-28'),
      dueDate: new Date('2026-01-05'),
      completedDate: new Date('2026-01-05'),
      technician: 'Regional Metrology Testing Laboratory',
      cost: 3200,
      description: 'Annual ISO 17025 calibration certification and probe compensation testing.',
      status: 'Completed',
      priority: 'Low',
      notes: 'Calibration certificate valid until January 2027.',
      scheduledBy: headUser._id,
    },
    {
      asset: createdAssets[5]._id, // APC UPS
      maintenanceType: 'Preventive',
      scheduledDate: new Date('2026-01-15'),
      dueDate: new Date('2026-01-20'),
      completedDate: new Date('2026-01-20'),
      technician: 'Schneider Electric Field Engineer',
      cost: 1200,
      description: 'Battery health load discharge test and SNMP firmware upgrade.',
      status: 'Completed',
      priority: 'Medium',
      notes: 'Battery pack health 94%. Next replacement planned in 2028.',
      scheduledBy: adminUser._id,
    },
    {
      asset: createdAssets[8]._id, // MakerBot 3D Printer
      maintenanceType: 'Preventive',
      scheduledDate: new Date('2026-10-15'),
      dueDate: new Date('2026-10-20'),
      technician: 'Rapid Tech Support Services',
      cost: 2500,
      description: 'Scheduled extruder nozzle replacement and dual lead screw axis lubrication.',
      status: 'Scheduled',
      priority: 'Medium',
      notes: 'Consumable nozzles already in store shelf B-4.',
      scheduledBy: staffUser._id,
    },
    {
      asset: createdAssets[6]._id, // Cisco Switch
      maintenanceType: 'Preventive',
      scheduledDate: new Date('2026-02-25'),
      dueDate: new Date('2026-03-01'),
      completedDate: new Date('2026-03-01'),
      technician: 'Er. Rajesh Kumar',
      cost: 0,
      description: 'Cisco IOS-XE security vulnerability patch and fan speed diagnostic.',
      status: 'Completed',
      priority: 'High',
      notes: 'Uptime 412 days without packet loss.',
      scheduledBy: adminUser._id,
    },
  ];

  await Maintenance.insertMany(maintenanceRecords);
  console.log('Seeded 8 Maintenance records.');

  // 6. Create Usage / Check-out Records
  const usageRecordsData = [
    {
      asset: createdAssets[2]._id, // Rigol Oscilloscope
      user: staffUser._id,
      action: 'CHECK_OUT',
      department: deptMap['ECE']._id,
      location: locMap['LOC-ECE-01']._id,
      purpose: 'Digital Signal Processing lab practical demonstration for ECE Semester 5 students.',
      checkOutDate: new Date('2026-09-28T09:30:00Z'),
      expectedReturnDate: new Date('2026-10-03T17:00:00Z'),
      actualReturnDate: null,
      conditionBefore: 'Good',
      status: 'ACTIVE',
      notes: 'Issued along with 2x 100MHz passive probes.',
      recordedBy: staffUser._id,
    },
    {
      asset: createdAssets[8]._id, // MakerBot 3D Printer
      user: staffUser._id,
      action: 'CHECK_OUT',
      department: deptMap['MECH']._id,
      location: locMap['LOC-MECH-WS']._id,
      purpose: 'Fabricating planetary gearbox casing for National Robotics Championship prototype.',
      checkOutDate: new Date('2026-09-29T11:00:00Z'),
      expectedReturnDate: new Date('2026-10-04T18:00:00Z'),
      actualReturnDate: null,
      conditionBefore: 'Good',
      status: 'ACTIVE',
      notes: 'Using red PLA filament spool #04.',
      recordedBy: staffUser._id,
    },
    {
      asset: createdAssets[3]._id, // Fluke Multimeter
      user: headUser._id,
      action: 'CHECK_IN',
      department: deptMap['ECE']._id,
      location: locMap['LOC-ECE-01']._id,
      purpose: 'Faculty research circuit board testing.',
      checkOutDate: new Date('2026-09-22T10:00:00Z'),
      expectedReturnDate: new Date('2026-09-24T17:00:00Z'),
      actualReturnDate: new Date('2026-09-24T16:45:00Z'),
      conditionBefore: 'Excellent',
      conditionAfter: 'Excellent',
      status: 'RETURNED',
      notes: 'Returned on schedule in clean original hardcase.',
      recordedBy: staffUser._id,
    },
    {
      asset: createdAssets[0]._id, // Dell Desktop
      user: staffUser._id,
      action: 'CHECK_IN',
      department: deptMap['CSE']._id,
      location: locMap['LOC-CSE-01']._id,
      purpose: 'Semester practical examination seat allocation.',
      checkOutDate: new Date('2026-09-15T08:30:00Z'),
      expectedReturnDate: new Date('2026-09-18T18:00:00Z'),
      actualReturnDate: new Date('2026-09-18T17:30:00Z'),
      conditionBefore: 'Excellent',
      conditionAfter: 'Excellent',
      status: 'RETURNED',
      notes: 'Verified login credentials and cleared student temporary user folders.',
      recordedBy: adminUser._id,
    },
    {
      asset: createdAssets[21]._id, // Wireless mic
      user: headUser._id,
      action: 'CHECK_IN',
      department: deptMap['ADMIN']._id,
      location: locMap['LOC-SEM-01']._id,
      purpose: 'Guest Lecture on Next-Gen Artificial Intelligence by IIT Professor.',
      checkOutDate: new Date('2026-09-10T13:30:00Z'),
      expectedReturnDate: new Date('2026-09-10T18:00:00Z'),
      actualReturnDate: new Date('2026-09-10T17:50:00Z'),
      conditionBefore: 'Excellent',
      conditionAfter: 'Excellent',
      status: 'RETURNED',
      notes: 'AA batteries removed before storing in microphone locker.',
      recordedBy: staffUser._id,
    },
    {
      asset: createdAssets[4]._id, // Epson Projector
      user: staffUser._id,
      action: 'STATUS_CHANGE',
      department: deptMap['ADMIN']._id,
      location: locMap['LOC-SEM-01']._id,
      purpose: 'Overheating notification from seminar coordinator.',
      checkOutDate: new Date('2026-09-25T14:00:00Z'),
      conditionBefore: 'Good',
      conditionAfter: 'Fair',
      status: 'RETURNED',
      notes: 'Changed status to Under Maintenance and dispatched service ticket.',
      recordedBy: staffUser._id,
    },
    {
      asset: createdAssets[20]._id, // Waveform Generator
      user: staffUser._id,
      action: 'STATUS_CHANGE',
      department: deptMap['ECE']._id,
      location: locMap['LOC-ECE-01']._id,
      purpose: 'Student reported distorted sine wave output during analog lab exam.',
      checkOutDate: new Date('2026-09-20T11:15:00Z'),
      conditionBefore: 'Good',
      conditionAfter: 'Poor',
      status: 'RETURNED',
      notes: 'Marked as Damaged; tagged with yellow repair caution label.',
      recordedBy: staffUser._id,
    },
  ];

  await UsageRecord.insertMany(usageRecordsData);
  console.log('Seeded Usage circulation records.');

  // 7. Seed Notifications
  const notificationsData = [
    {
      title: 'Low Stock Alert: Arduino Uno Starter Kits',
      message: 'Current quantity in Central Store is 4 units (Threshold: 6). Reorder suggested for upcoming Semester 4 embedded lab.',
      type: 'LOW_STOCK',
      priority: 'warning',
      entityType: 'Asset',
      entityId: createdAssets[9]._id.toString(),
      isRead: false,
      targetRole: 'ALL',
      link: `/assets/${createdAssets[9]._id}`,
    },
    {
      title: 'Low Stock Alert: Raspberry Pi 4B (8GB)',
      message: 'Only 3 units remaining in stock (Minimum threshold: 5). High demand for IoT mini-projects.',
      type: 'LOW_STOCK',
      priority: 'warning',
      entityType: 'Asset',
      entityId: createdAssets[10]._id.toString(),
      isRead: false,
      targetRole: 'ALL',
      link: `/assets/${createdAssets[10]._id}`,
    },
    {
      title: 'Maintenance Due Soon: Epson EB-X06 Projector',
      message: 'Scheduled cooling fan replacement due in 2 days (October 2, 2026). Technician assigned: Vignesh AV Support.',
      type: 'MAINTENANCE_DUE',
      priority: 'warning',
      entityType: 'Maintenance',
      entityId: createdAssets[4]._id.toString(),
      isRead: false,
      targetRole: 'ALL',
      link: `/maintenance`,
    },
    {
      title: 'Maintenance Overdue: Digital Waveform Generator',
      message: 'Calibration service overdue since September 27. Action required to restore unit for ECE lab use.',
      type: 'MAINTENANCE_OVERDUE',
      priority: 'danger',
      entityType: 'Maintenance',
      entityId: createdAssets[20]._id.toString(),
      isRead: false,
      targetRole: 'ALL',
      link: `/maintenance`,
    },
    {
      title: 'Asset Returned In Good Condition',
      message: 'Fluke 115 True-RMS Digital Multimeter returned to ECE Lab by Dr. K. S. Ramanathan.',
      type: 'STATUS_CHANGE',
      priority: 'info',
      entityType: 'Asset',
      entityId: createdAssets[3]._id.toString(),
      isRead: true,
      targetRole: 'ALL',
      link: `/assets/${createdAssets[3]._id}`,
    },
    {
      title: 'System Startup: Database Initialized',
      message: 'Smart Inventory & Asset Management System database initialized with verified college departments, locations, and assets.',
      type: 'SYSTEM',
      priority: 'info',
      entityType: 'System',
      entityId: '',
      isRead: true,
      targetRole: 'ALL',
      link: `/dashboard`,
    },
  ];

  await Notification.insertMany(notificationsData);
  console.log('Seeded Notifications.');

  // 8. Seed Audit Logs
  const auditLogsData = [
    {
      user: adminUser._id,
      userName: 'Prof. Suresh Kumar (Admin)',
      userRole: 'ADMIN',
      action: 'SYSTEM_INIT',
      entity: 'System',
      entityId: 'SYS-01',
      details: 'System configured with 6 academic departments and 8 campus locations.',
      ipAddress: '192.168.1.10',
    },
    {
      user: staffUser._id,
      userName: 'Er. Eniya Siva (Staff)',
      userRole: 'STAFF',
      action: 'CHECK_OUT',
      entity: 'Asset',
      entityId: 'AST-2026-0003',
      details: 'Staff checked out Rigol DS1054Z Digital Oscilloscope for DSP practicals.',
      ipAddress: '192.168.1.42',
    },
    {
      user: staffUser._id,
      userName: 'Er. Eniya Siva (Staff)',
      userRole: 'STAFF',
      action: 'CHECK_OUT',
      entity: 'Asset',
      entityId: 'AST-2026-0009',
      details: 'Staff checked out MakerBot Replicator+ 3D Printer for student robotics work.',
      ipAddress: '192.168.1.42',
    },
    {
      user: headUser._id,
      userName: 'Dr. K. S. Ramanathan (HOD)',
      userRole: 'DEPARTMENT_HEAD',
      action: 'VIEW_REPORT',
      entity: 'Report',
      entityId: 'RPT-DEPT',
      details: 'Department Head generated and reviewed CSE Department Asset Valuation summary.',
      ipAddress: '192.168.1.25',
    },
    {
      user: adminUser._id,
      userName: 'Prof. Suresh Kumar (Admin)',
      userRole: 'ADMIN',
      action: 'SCHEDULE_MAINTENANCE',
      entity: 'Maintenance',
      entityId: 'AST-2026-0005',
      details: 'Admin scheduled corrective service for Epson EB-X06 Projector.',
      ipAddress: '192.168.1.10',
    },
    {
      user: staffUser._id,
      userName: 'Er. Eniya Siva (Staff)',
      userRole: 'STAFF',
      action: 'CHECK_IN',
      entity: 'Asset',
      entityId: 'AST-2026-0004',
      details: 'Staff recorded check-in for Fluke 115 Digital Multimeter in good condition.',
      ipAddress: '192.168.1.42',
    },
  ];

  await AuditLog.insertMany(auditLogsData);
  console.log('Seeded Audit Logs.');
  console.log('--- Database Seeding Completed Successfully ---');
}
